version: "1.0"
services:
  esmfe:
    container_name: esmfe
    image: "snowflower1408/esmfe"
    #ports:
    #  - "80:80"
    environment:
      VIRTUAL_HOST: esm.laptrinhkhongvui.com
      LETSENCRYPT_HOST: esm.laptrinhkhongvui.com

  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    environment:
      DHPARAM_GENERATION: "false" # disable auto param generation
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./etc/nginx/certs:/etc/nginx/certs
      - ./etc/nginx/vhost.d:/etc/nginx/vhost.d
      - nginx_proxy_html:/usr/share/nginx/html

  nginx-proxy-letencrypt:
    container_name: nginx-proxy-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./etc/nginx/certs:/etc/nginx/certs
      - ./etc/nginx/vhost.d:/etc/nginx/vhost.d
      - nginx_proxy_html:/usr/share/nginx/html
    environment:
      DEFAULT_EMAIL: example@gmail.com
      NGINX_PROXY_CONTAINER: nginx-proxy

volumes:
  nginx_proxy_html:
