import { ChangeDetectionStrategy, Component } from '@angular/core';
import {
  FormArray,
  FormControl,
  FormGroup,
  NonNullableFormBuilder,
  Validators,
} from '@angular/forms';
import { tuiButtonOptionsProvider } from '@taiga-ui/core';
import { BehaviorSubject } from 'rxjs';

type Item = {
  id: string;
  moduleId: string;
  moduleName: string;
  type: string;
  startAt: Date;
  shift: number;
  room: string;
  candidatesCount: number;
  invigilatorsCount: Record<string, number>;
};

@Component({
  templateUrl: './assign-faculty.component.html',
  styleUrls: ['./assign-faculty.component.less'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [tuiButtonOptionsProvider({ size: 'm' })],
})
export class InvigilatorAssignFacultyComponent {
  // PUBLIC PROPERTIES
  data: Item[] = data;
  isEditing = false;
  readonly isSaving$ = new BehaviorSubject<boolean>(false);
  readonly facultiesId = Object.keys(this.data[0].invigilatorsCount);

  columns = [
    'moduleId',
    'moduleName',
    'type',
    'startAt',
    'shift',
    'room',
    'candidatesCount',
    ...this.facultiesId,
  ];
  readonly form!: FormGroup;

  // CONSTRUCTOR
  constructor(private readonly fb: NonNullableFormBuilder) {
    this.form = this.fb.group({
      invigilatorsCount: this.fb.array(
        this.data.map((item) =>
          this.fb.group(
            Object.entries(item.invigilatorsCount).reduce(
              (acc, [key, value]) => {
                acc[key] = [value, [Validators.required, Validators.min(0)]];
                return acc;
              },
              {} as Record<string, any>
            )
          )
        )
      ),
    });

    this.form.disable();
  }

  // PUBLIC METHODS
  onValueChange(id: string, value: number): void {
    for (const item of this.data) {
      if (item.id === id) {
        item.candidatesCount = value;
        break;
      }
    }

    this.data = this.data;
  }

  invigilatorsCount(index: number): FormGroup {
    return (this.form.controls['invigilatorsCount'] as FormArray).at(
      index
    ) as FormGroup;
  }

  control(index: number, controlName: string): FormControl {
    return this.invigilatorsCount(index).controls[controlName] as FormControl;
  }

  saveChange(): void {
    this.isSaving$.next(true);
    setTimeout(() => {
      data = (this.form.controls['invigilatorsCount'] as FormArray).value;
      this.toggleEdit(false);
      this.isSaving$.next(false);
    }, 1000);
  }

  cancelEdit(): void {
    (this.form.controls['invigilatorsCount'] as FormArray).patchValue(data);
    this.toggleEdit(false);
  }

  toggleEdit(isEditing: boolean): void {
    this.isEditing = isEditing;
    if (isEditing) {
      this.form.enable();
    } else {
      this.form.disable();
    }
  }
}

let data: Item[] = [
  {
    id: '1',
    moduleId: 'BS0.001.2',
    moduleName: 'Giải tích 1',
    type: 'Trắc nghiệm',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 100,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
  {
    id: '2',
    moduleId: 'BS0.001.2',
    moduleName: 'Giải tích 1',
    type: 'Trắc nghiệm',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 100,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
  {
    id: '3',
    moduleId: 'BS0.001.2',
    moduleName: 'Giải tích 1',
    type: 'Trắc nghiệm',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 100,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
  {
    id: '4',
    moduleId: 'BS0.001.2',
    moduleName: 'Giải tích 1',
    type: 'Trắc nghiệm',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 100,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
  {
    id: '5',
    moduleId: 'BS0.101.3',
    moduleName: 'Đại số tuyến tính',
    type: 'Tự luận',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 55,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
  {
    id: '6',
    moduleId: 'BS0.101.3',
    moduleName: 'Đại số tuyến tính',
    type: 'Tự luận',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 55,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
  {
    id: '7',
    moduleId: 'BS0.101.3',
    moduleName: 'Đại số tuyến tính',
    type: 'Tự luận',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 55,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
  {
    id: '8',
    moduleId: 'BS0.101.3',
    moduleName: 'Đại số tuyến tính',
    type: 'Tự luận',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 55,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
  {
    id: '9',
    moduleId: 'BS0.001.2',
    moduleName: 'Giải tích 1',
    type: 'Trắc nghiệm',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 100,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
  {
    id: '10',
    moduleId: 'BS0.001.2',
    moduleName: 'Giải tích 1',
    type: 'Trắc nghiệm',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 100,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
  {
    id: '13',
    moduleId: 'BS0.001.2',
    moduleName: 'Giải tích 1',
    type: 'Trắc nghiệm',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 100,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
  {
    id: '14',
    moduleId: 'BS0.001.2',
    moduleName: 'Giải tích 1',
    type: 'Trắc nghiệm',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 100,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
  {
    id: '15',
    moduleId: 'BS0.101.3',
    moduleName: 'Đại số tuyến tính',
    type: 'Tự luận',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 55,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
  {
    id: '16',
    moduleId: 'BS0.101.3',
    moduleName: 'Đại số tuyến tính',
    type: 'Tự luận',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 55,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
  {
    id: '17',
    moduleId: 'BS0.101.3',
    moduleName: 'Đại số tuyến tính',
    type: 'Tự luận',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 55,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
  {
    id: '18',
    moduleId: 'BS0.101.3',
    moduleName: 'Đại số tuyến tính',
    type: 'Tự luận',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 55,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
  {
    id: '11',
    moduleId: 'BS0.001.2',
    moduleName: 'Giải tích 1',
    type: 'Trắc nghiệm',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 100,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
  {
    id: '12',
    moduleId: 'BS0.001.2',
    moduleName: 'Giải tích 1',
    type: 'Trắc nghiệm',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 100,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
  {
    id: '13',
    moduleId: 'BS0.001.2',
    moduleName: 'Giải tích 1',
    type: 'Trắc nghiệm',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 100,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
  {
    id: '14',
    moduleId: 'BS0.001.2',
    moduleName: 'Giải tích 1',
    type: 'Trắc nghiệm',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 100,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
  {
    id: '15',
    moduleId: 'BS0.101.3',
    moduleName: 'Đại số tuyến tính',
    type: 'Tự luận',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 55,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
  {
    id: '16',
    moduleId: 'BS0.101.3',
    moduleName: 'Đại số tuyến tính',
    type: 'Tự luận',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 55,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
  {
    id: '17',
    moduleId: 'BS0.101.3',
    moduleName: 'Đại số tuyến tính',
    type: 'Tự luận',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 55,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
  {
    id: '18',
    moduleId: 'BS0.101.3',
    moduleName: 'Đại số tuyến tính',
    type: 'Tự luận',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 55,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
  {
    id: '19',
    moduleId: 'BS0.001.2',
    moduleName: 'Giải tích 1',
    type: 'Trắc nghiệm',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 100,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
  {
    id: '110',
    moduleId: 'BS0.001.2',
    moduleName: 'Giải tích 1',
    type: 'Trắc nghiệm',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 100,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
  {
    id: '113',
    moduleId: 'BS0.001.2',
    moduleName: 'Giải tích 1',
    type: 'Trắc nghiệm',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 100,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
  {
    id: '114',
    moduleId: 'BS0.001.2',
    moduleName: 'Giải tích 1',
    type: 'Trắc nghiệm',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 100,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
  {
    id: '115',
    moduleId: 'BS0.101.3',
    moduleName: 'Đại số tuyến tính',
    type: 'Tự luận',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 55,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
  {
    id: '116',
    moduleId: 'BS0.101.3',
    moduleName: 'Đại số tuyến tính',
    type: 'Tự luận',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 55,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
  {
    id: '117',
    moduleId: 'BS0.101.3',
    moduleName: 'Đại số tuyến tính',
    type: 'Tự luận',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 55,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
  {
    id: '118',
    moduleId: 'BS0.101.3',
    moduleName: 'Đại số tuyến tính',
    type: 'Tự luận',
    startAt: new Date(),
    shift: 2,
    room: '403-A4',
    candidatesCount: 55,
    invigilatorsCount: {
      khcb: 7,
      ck: 1,
      ct: 3,
      ddt: 1,
      ktxd: 1,
      vtkt: 1,
      mtatgt: 1,
      llct: 1,
      qlxd: 0,
      cntt: 0,
    },
  },
];
