name: Deploy

on:
  push:
    branches: ["prod"]

jobs:
  build:
    name: Build Prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.4.0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.20.0

      - name: Generate env files
        run: node ./scripts/env.js
        env:
          BASE_URL: "${{ secrets.BASE_URL }}"
          DEFAULT_PASSWORD: "${{ secrets.DEFAULT_PASSWORD }}"
          SYNCFUSION_LICENSE: "${{ secrets.SYNCFUSION_LICENSE }}"
          RECAPTCHA_SITE_KEY: "${{ secrets.RECAPTCHA_SITE_KEY }}"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: npm run build:prod

      - name: Copy bundle to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PWD }}
          source: "./dist/esm-fe/*"
          target: "/var/www/esm"
          strip_components: 2
          overwrite: true
