name: Deploy

on:
  push:
    branches: ["prod"]

jobs:
  build:
    name: Build Prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        run: npm run build:prod
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          SYNCFUSION_LICENSE: ${{ secrets.SYNCFUSION_LICENSE }}
          RECAPTCHA_SITE_KEY: ${{ secrets.RECAPTCHA_SITE_KEY }}

      - name: Copy bundle to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PWD }}
          source: "./dist/esm-fe/*"
          target: "/var/www/esm"
          strip_components: 2
          overwrite: true
