name: Sonar Analysis
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  checkout:
    name: Checkout
    uses: actions/checkout@v3

  setup:
    name: Setup
    uses: ./.github/actions/setup

  sonar-cloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Test and coverage
        run: npm run test:ci

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets. SONARCLOUD_TOKEN }}
