name: Sonar Analysis

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar-cloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.4.0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.20.0

      - name: Generate env files
        run: node ./scripts/env.js
        env:
          BASE_URL: "${{ secrets.BASE_URL }}"
          DEFAULT_PASSWORD: "${{ secrets.DEFAULT_PASSWORD }}"
          SYNCFUSION_LICENSE: "${{ secrets.SYNCFUSION_LICENSE }}"
          RECAPTCHA_SITE_KEY: "${{ secrets.RECAPTCHA_SITE_KEY }}"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test and coverage
        run: npm run test:ci

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets. SONARCLOUD_TOKEN }}
